# Generated by Django 5.1 on 2024-12-31 12:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_favorite_date_end_alter_favorite_date_start'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'object')},
        ),
    ]
